// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import * as THREE from "three";
// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { GLTF } from "three-stdlib";

// type GLTFResult = GLTF & {
//   nodes: {
//     mesh_0: THREE.Mesh;
//   };
//   materials: {};
// };

// export function Model(props: JSX.IntrinsicElements["group"]) {
//   const { nodes, materials } = useGLTF(
//     "/Models/uploads_files_6203010_Futuristic+Combat+Robot+Soldier+(1).glb"
//   ) as GLTFResult;
//   return (
//     <group {...props} dispose={null} scale={2.8} position={[0, 0.2, 0]}>
//       <group>
//         <mesh
//           name="mesh_0"
//           castShadow
//           receiveShadow
//           geometry={nodes.mesh_0.geometry}
//           material={nodes.mesh_0.material}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload(
//   "/uploads_files_6203010_Futuristic+Combat+Robot+Soldier+(1).glb"
// );

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Updated for Steampunk Carnival Game model
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.Material>;
};

export function Model(props: React.ComponentProps<'group'>) {
  const { scene } = useGLTF(
    "/Models/pandaren_style_hot_air_balloon.glb"
  ) as unknown as GLTFResult;

  const group = useRef<THREE.Group>(null!);
  
  // Base position that you can easily change
  const basePosition: [number, number, number] = [0, -1.6, 0];
  const baseScale = 0.25;

  // Keep original colors, just ensure shadows are enabled
  React.useEffect(() => {
    scene.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        mesh.castShadow = true;
        mesh.receiveShadow = true;
      }
    });
  }, [scene]);

  // Smooth floating animation for hot air balloon - works relative to base position
  useFrame(({ clock }) => {
    const t = clock.getElapsedTime();
    if (group.current) {
      // Gentle vertical floating motion (added to base Y position)
      group.current.position.y = basePosition[1] + Math.sin(t * 0.5) * 0.2;
      // Slight horizontal sway (added to base X position)
      group.current.position.x = basePosition[0] + Math.sin(t * 0.3) * 0.1;
      // Keep base Z position
      group.current.position.z = basePosition[2];
      // Subtle rotation
      group.current.rotation.y = Math.sin(t * 0.2) * 0.05;
    }
  });

  return (
    <group ref={group} {...props} dispose={null} scale={baseScale}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/Models/pandaren_style_hot_air_balloon.glb");