// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import * as THREE from "three";
// import React, { useRef } from "react";
// import { useGLTF } from "@react-three/drei";
// import { GLTF } from "three-stdlib";

// type GLTFResult = GLTF & {
//   nodes: {
//     mesh_0: THREE.Mesh;
//   };
//   materials: {};
// };

// export function Model(props: JSX.IntrinsicElements["group"]) {
//   const { nodes, materials } = useGLTF(
//     "/Models/uploads_files_6203010_Futuristic+Combat+Robot+Soldier+(1).glb"
//   ) as GLTFResult;
//   return (
//     <group {...props} dispose={null} scale={2.8} position={[0, 0.2, 0]}>
//       <group>
//         <mesh
//           name="mesh_0"
//           castShadow
//           receiveShadow
//           geometry={nodes.mesh_0.geometry}
//           material={nodes.mesh_0.material}
//         />
//       </group>
//     </group>
//   );
// }

// useGLTF.preload(
//   "/uploads_files_6203010_Futuristic+Combat+Robot+Soldier+(1).glb"
// );

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Updated for Steampunk Carnival Game model
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: Record<string, THREE.Mesh>;
  materials: Record<string, THREE.Material>;
};

export function Model(props: React.ComponentProps<'group'>) {
  const { scene } = useGLTF(
    "/Models/dae_bazaar_steampunk_carnival_game.glb"
  ) as unknown as GLTFResult;

  const group = useRef<THREE.Group>(null!);

  // Keep original colors, just ensure shadows are enabled
  React.useEffect(() => {
    scene.traverse((child) => {
      if ((child as THREE.Mesh).isMesh) {
        const mesh = child as THREE.Mesh;
        mesh.castShadow = true;
        mesh.receiveShadow = true;
      }
    });
  }, [scene]);

  // Smooth floating animation only - no rotation
  useFrame(({ clock }) => {
    const t = clock.getElapsedTime();
    if (group.current) {
      // Only gentle vertical floating, no rotation
      group.current.position.y = -0.5 + Math.sin(t * 0.4) * 0.12; // Smooth floating
    }
  });

  return (
    <group ref={group} {...props} dispose={null} scale={0.8} position={[0, -0.5, 0]}>
      <primitive object={scene} />
    </group>
  );
}

useGLTF.preload("/Models/dae_bazaar_steampunk_carnival_game.glb");